version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name test-kadai --s3-location s3://mys3-codekadai/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src